### PR TITLE
Version 2.0

### PR DESCRIPTION
**Pull request by jshcrowthe**
# Version 2.0 Release

I have decided to approach the problem a little differently. In doing so I have made some breaking changes but have simplified the API drastically.

## Breaking Changes

Lets get these out of the way up front. Lots of changes:

- No longer exposes the elements `wc-i18n` or `wc-i18n-src`
- Refactored behavior name from `WCI18nBehavior` -> `WCI18n`
- Behavior is now a function instead of just an object, (you must call the function)
- Temporarily removed the mapping function `_localeMapper` (This will be added in `v2.1`)
- Languages are now set on a page level via `WCI18n.setLocale`

## The new API

Before the API required **way** to much boilerplate to actually get functioning well. This refactor has eliminated a lot of that and simplified it to three things. Consider the component below:

```html
<link rel="import" href="../polymer/polymer.html">
<link rel="import" href="../wc-i18n/wc-i18n.html">

<dom-module id="v2-comp">
  <template>
    <style>
      :host {
        display: block;
      }
    </style>
    <h1>[[_i18n.KEY_NAME]]</h1>
  </template>
  <script>
    Polymer({
      is: 'v2-comp',
      behaviors: [
        WCI18n('v2-comp')
      ]
    });
  </script>
</dom-module>
```

There are 3 keys to using this component:
- `<link rel="import" href="../wc-i18n/wc-i18n.html">`
- `WCI18n('v2-comp')`
- `[[_i18n.KEY_NAME]]`

The first two points are the only boilerplate required to bootstrap your component's translations. The first is pretty self explanatory, HTML import `wc-i18n.html` into your application. The second is the inclusion of the `WCI18n` behavior. This is a function that must be called with the name of your component (the same value that is set as the `is` attribute). It will then, for local dev, look in the `locales` directory for the locales as before.

After those two steps, you simply use the `_i18n` object provided to you as a part of the behavior. You are also given 3 methods that you can use:

- `setLocales(lang, locales)`: This method will allow you to override the locales for a given component. NOTE: This will modify **all** instances of this component throughout the app.
- `getLocales(lang)`: This method fetches the locales for a given language and returns them as an object.
- `translate(string, lang)`: This method translates a given string to the passed language.

_NOTE: In all instances, the language, if not passed, defaults to `WCI18n.getLocale()`_

Most people will use the `_i18n` object and data bind to it inside of their applications.

## Prod Use

There is a [PR on gulp-wc-i18n](https://github.com/jshcrowthe/gulp-wc-i18n/pull/1) to support this change. See the docs there on inlining translations for production usage.

### CODE REVIEW

**Comment by marcelklehr** [comment]
Hey! Great to see someone else is thinking about this!

I have the following question regarding this proposal: How will translations be loaded? I would like to allow the page author to specify where they come from and allow the component author to just make use of the translate function. I think a `<link>`-style custom element for specifying where translations come from would still be a nice thing, as it's declarative.

**Comment by marcelklehr** [comment]
Oh, and using <html lang=""> as input would make sense, too, IMO.

**Comment by jshcrowthe** [comment]
@marcelklehr the translations are being loaded in two different ways (depending on the environment):

### Dev
The files are loaded via `AJAX` (in my implementation I use `fetch` instead of `XMLHttpRequest`). Based on which language is currently set for the application (ATM v2 of`wc-i18n` only allows 1).

### Prod
You would either inline your resources (similar to how it is done in https://github.com/PolymerElements/app-localize-behavior) at dev time **or** you can use a tool like https://github.com/jshcrowthe/gulp-wc-i18n to inline them for you at build time. Either way, you don't want to have a network request, per component, to render text to the screen (that can get costly real fast).

Again, app-localize-behavior handles this by letting you pass a `resources` prop or by specifying the location of 1 large locale file. This file gets cached so using `AJAX` to load it (which IMO isn't optimal due to the network request), totally works because the request is really only made once.

### Customizing locale loading
So, to your point. We could definitely allow the extension of the loading behavior for and look for an optional function `loadLocales` function (or similar) that returns a `Promise`. 
That promise would then just need to resolve with an object formatted as follows:

```javascript
{
  en: {
    key: 'value'
  },
  fr: {
    key: 'valeur'
  }
}
```

That could totally work. Thoughts?

I had originally defined the loading behavior in the `v1` iteration of this as a component called `wc-i18n-src`. However it required a large amount of boilerplate just to get it working which I thought was sub-optimal. `v2` gets us to a place I feel is much cleaner (the whole piece of functionality implemented as a behavior), and reduces the boilerplate significantly.

**Comment by jshcrowthe** [comment]
**NOTE: The API for this component has changed since the original PR. See [this commit](https://github.com/jshcrowthe/wc-i18n/blob/51bdf773072afcd954e46311d0a80fe0d62f7dec/README.md) for the updated API**

**Comment by marcelklehr** [comment]
I made assumptions about the architecture of Polymer apps that turned out to be wrong. I think the current version is very good. To improve it further, http://formatjs.io/ could be used (especially the ICU message format is really worth adopting). Also, from reading the README I'm not sure where the app-global language is set (for this `<html lang="">` could be used, but I don't know if this is still the state of-the-art way to do that ;) ).

**Comment by jshcrowthe** [comment]
Originally I wanted to use the `IntlMessageFormat` but the polyfill for the `Intl` object with its locales is huge.

That said http://caniuse.com/#feat=internationalization shows that IE 11 even supports this (Safari 9.1 was the only straggler), so maybe the Polyfill need is moot.

It'd even let us extend the API a little and make it more flexible.

**Comment by jshcrowthe** [comment]
For the default language, I would lean towards `navigator.language` or `en` as defaults. 

The only problem is building the language fallback when you get two codes that need to fallback to a common root:

_e.g._
- `en-US`
- `en-UK`

_These both fallback to `en`_

The declarative method would be to define the language on **any** component as they will all end up using the same value.

**Pull request merged**
